version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - database
      - redis
    ports:
      - "8094:8094"
    container_name: bus_server
    hostname: bus_app
    volumes:
      - ./uploads:/apps/uploads 
      - ./build:/opt/tomcat/webapps
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bus?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yi0535551333@
      SPRING_PROFILES_ACTIVE: dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - bus

  database:
    image: ubuntu/mysql
    container_name: bus_db
    restart: always
    environment:
      - MYSQL_DATABASE=bus
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=yi0535551333@

    ports:
      - "23306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - bus
    hostname: bus_database
    cap_add:
      - SYS_NICE

  redis:
    image: redis:latest
    container_name: bus-redis-server
    networks:
      - bus
    ports:
      - 16379:6379


networks:
  bus:
