server.port=8094

# CORS setting
spring.web.cors.allowed-origin-patterns=https://localhost:8094

## Redis Setting
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=6000

# Redis connection pool
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=-1ms

#??? ???
file.upload.found-location=uploads/found/
file.url-prefix=uploads/found/
file.upload.ad-location=uploads/ad/

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kyb4218@gmail.com
spring.mail.password=ewyipwgnthghsmno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SQL ?? ??
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace


redirect.base-url=https://localhost:5173
redirect.admin-path=/admin/dashboard
redirect.user-path=/mypage
